development: &default
  adapter: postgresql
  encoding: unicode
  database: spotlight_development
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: spotlight_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
